<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.10.0" xml:lang="en-US">
  <compounddef id="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached" kind="class" language="Python" prot="public">
    <compoundname>game::utils::exceptions::MaxPlayersReached</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached_1af2189f07dc3d02224744605f71b0f7a4" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>game.utils.exceptions.MaxPlayersReached.__init__</definition>
        <argsstring>(self, message=&quot;The player number limit has been reached, please come back later.&quot;)</argsstring>
        <name>__init__</name>
        <qualifiedname>game.utils.exceptions.MaxPlayersReached.__init__</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;The player number limit has been reached, please come back later.&quot;</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="68" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="68" bodyend="70"/>
        <references refid="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached_1af2189f07dc3d02224744605f71b0f7a4" compoundref="exceptions_8py" startline="68" endline="70">game.utils.exceptions.MaxPlayersReached.__init__</references>
        <referencedby refid="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached_1af2189f07dc3d02224744605f71b0f7a4" compoundref="exceptions_8py" startline="68" endline="70">game.utils.exceptions.MaxPlayersReached.__init__</referencedby>
      </memberdef>
    </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Class for creating the exception caused by reaching the maximum player count of a server.
</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>game.utils.exceptions.MaxPlayersReached</label>
        <link refid="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>game.utils.exceptions.MaxPlayersReached</label>
        <link refid="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="63" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="63" bodyend="70"/>
    <listofallmembers>
      <member refid="classgame_1_1utils_1_1exceptions_1_1MaxPlayersReached_1af2189f07dc3d02224744605f71b0f7a4" prot="public" virt="non-virtual"><scope>game::utils::exceptions::MaxPlayersReached</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
